// lib/copy.js
export const copy = {
  checkoutUrl: "https://www.oriopay.app/p/natuurlijke-cosmetica",

  metadata: {
    title: "Gids voor Natuurlijke Cosmetica",
    description:
      "80 recepten voor 100% natuurlijke cosmetica om thuis te maken. Geteste en bewezen formules voor veilige huidverzorging en het vermijden van giftige chemicaliën.",
  },

  hero: {
    headlineLine1: "80 recepten voor",
    headlineHighlight: "NATUURLIJKE COSMETICA",
    subheadline:
      "Krijg toegang tot geheime recepten voor 100% natuurlijke cosmetica die je gewoon thuis kunt maken! Geteste en veilige formules om de gezondheid van je gezin te beschermen en te stoppen met industriële producten vol gifstoffen.",
    cta: "IK WIL NU TOEGANG!",
    imageAlt: "Gids voor natuurlijke cosmetica",
    timerLabels: {
      days: "Dagen",
      hours: "Uren",
      minutes: "Minuten",
      seconds: "Seconden",
    },
  },

  story: {
    text: "Ik ga je nu een praktische, to-the-point en uiterst betrouwbare gids geven waarmee je thuis je eigen 100% natuurlijke cosmetica kunt maken. Zonder een fortuin uit te geven, zonder afhankelijk te zijn van duizenden ingrediënten – en met het plezier om ze voor jezelf te gebruiken, als cadeau te geven aan je dierbaren, en samen te genieten van een 100% veilige en gezonde verzorging!",
    imageAlt: "Natuurlijke cosmetica",
  },

  recipeList: {
    headline: "Maak kennis met de",
    headlineHighlight: "80 recepten",
    headlineSuffix: "waar je toegang toe krijgt in de Gids voor Natuurlijke Cosmetica:",
    cta: "IK WIL ZE HEBBEN!",
    col1: [
      "Kalmerende bodycrème",
      "Bodycrème met panthenol",
      "Verfrissende bodylotion",
      "Body soufflé",
      "Body butter met urucum",
      "Vaste body butter (Lotionbar)",
      "Bodyolie",
      "Therapeutische olie voor vlekjes en striae",
      "Tweefasen bodyolie",
      "Natuurlijke zelfbruiner",
      "Vloeibare lichaamszeep",
      "Douchegel",
      "Vaste lichaamszeep met SCI",
      "Traditionele vaste lichaamszeep",
      "Romige hydraterende zeep",
      "Exfoliërende lichaamszeep (Scrubzeep)",
      "Bodyscrub",
      "Bodyscrub met amandelmeel",
      "Natuurlijke body highlighter",
      "Bodyspray (Body Splash)",
      "Gezichtscrème met vitamine C",
      "Aftersun gezichtscrème met lavendel",
      "Gezichtscrème met klei",
      "Hydraterende gezichtslotion met jasmijn",
      "Droge gezichtsolie (Dry Oil)",
      "Vloeibare gezichtszeep",
      "Reinigend gezichtsschuim",
      "Gezichtsserum voor de droge en gevoelige huid",
      "Gezichtsserum voor de vette huid",
      "Oogserum",
      "Gezichtstoner voor de droge en gevoelige huid",
      "Verfrissende gezichtstoner voor de vette huid",
      "Reinigingsolie voor het gezicht (Cleansing Oil)",
      "Reinigingsbalsem voor het gezicht (Cleansing Balm)",
      "Zeep met rode klei – Detox en revitalisatie",
      "Milde gezichtsscrub",
      "Gezichtsgel met salicylzuur",
      "Gel-gezichtsmasker met hyaluronzuur",
      "Gezichtselixer van rozen",
      "Gezichtsspray met aloë vera",
      "Haarmasker voor krullend en golvend haar",
    ],
    col2: [
      "Haarmasker voor steil en licht golvend haar",
      "Romige conditioner",
      "Solid conditioner voor krullend en golvend haar",
      "Solid conditioner voor licht golvend en steil haar",
      "Shampoobar voor krullend en golvend haar",
      "Shampoobar voor steil en licht golvend haar",
      "Vloeibare shampoo",
      "Romige 2-in-1 shampoo",
      "Kindershampoo",
      "Leave-in conditioner",
      "Hittebeschermende haarspray",
      "Haarolie",
      "Haargel",
      "Natuurlijke haarpommade",
      "Hydraterende finish spray",
      "Hoofdhuidscrub",
      "Haargroei toner",
      "Serum voor gespleten haarpunten",
      "Haarparfum",
      "Natuurlijke intiemzeep",
      "Natuurlijke kinderzeep voor het lichaam",
      "Natuurlijk vloeibaar parfum",
      "Natuurlijk vast parfum",
      "Tandpasta in gelvorm",
      "Mondwater",
      "Deodorant spray",
      "Calendulazalf",
      "Arnicazalf",
      "Voedende lippenbalsem",
      "Natuurlijke lippenstift",
      "Natuurlijke lipscrub",
      "Make-up remover spray",
      "Scheerschuim",
      "Natuurlijke aftershave",
      "Hand- en voetcrème",
      "Wenkbrauwgel",
      "Natuurlijke massagekaars",
      "Voedend serum voor nagels en nagelriemen",
      "Natuurlijk insectenwerend middel",
      "Revitaliserend badzout",
    ],
  },

  whatYouGet: {
    headline: "WAT ONTDEK JE IN DEZE COMPLETE GIDS?",
    cta: "KOOP DE GIDS NU!",
    imageAlt: "Wat je in de gids zult ontdekken",
    items: [
      "Meer dan 80 geteste en bewezen recepten – inclusief romige scrubzeep, droge gezichtsolie, bodyspray, hittebescherming voor het haar en diverse nieuwe innovatieve formules.",
      "Bases voor crèmes, gels, shampoos en zepen – leer hoe je 100% veilige en gepersonaliseerde formules maakt voor elk huid- en haartype.",
      "Een complete stap-voor-stap handleiding voor beginners en gevorderden – beheers alles, van de basisconcepten tot de meest complexe cosmetische technieken.",
      "Ingrediëntencatalogus – ontdek de voordelen van verschillende natuurlijke grondstoffen om hoogwaardige en zuivere cosmetica te creëren.",
      "Fytotherapie toegepast in de cosmetica – hoe je geneeskrachtige planten gebruikt om de werking van je cosmetica maximaal te versterken.",
      "De geheimen van natuurlijk formuleren – pH-waarde aanpassen, natuurlijke conservering, keuze van grondstoffen en de meest effectieve combinaties.",
      "Tips voor de perfecte thuisproductie – tover je keuken om tot een veilige plek om schone cosmetica te creëren en verfijn je technieken.",
      "Duurzaamheid en milieubewustzijn – leer volledig biologisch afbreekbare en ecologische cosmetica te maken die vriendelijk is voor onze planeet.",
    ],
  },

  testimonials: {
    headline: "BEKIJK WAT ANDERE VROUWEN ZEGGEN DIE DE GIDS AL GEBRUIKEN:",
    cta: "IK WIL NU TOEGANG!",
    cards: [
      {
        name: "Sanne M.",
        initials: "SM",
        color: "#16a34a",
        stars: 5,
        text: "Ik ben helemaal weg van deze gids! Ik heb de kalmerende bodycrème en de gezichtszeep al gemaakt en ze zijn fantastisch geworden. Veel beter dan de industriële producten die ik voorheen gebruikte. Een echte aanrader voor iedereen!",
        source: "WhatsApp",
      },
      {
        name: "Lotte de V.",
        initials: "LV",
        color: "#0f766e",
        stars: 5,
        text: "Meiden, wat een geweldige gids! De recepten zijn super gedetailleerd en makkelijk te volgen. Ik heb al een paar producten gemaakt als cadeau voor vriendinnen en ze zijn er dol op. Het is elke cent waard!",
        source: "WhatsApp",
      },
      {
        name: "Fleur R.",
        initials: "FR",
        color: "#7c3aed",
        stars: 5,
        text: "Ik twijfelde even om het te kopen, maar het was het absoluut waard! De grondstoffencatalogus heeft me enorm geholpen om de ingrediënten te begrijpen. Ik heb inmiddels al 6 verschillende recepten gemaakt en ze zijn allemaal perfect gelukt.",
        source: "WhatsApp",
      },
      {
        name: "Anne K.",
        initials: "AK",
        color: "#b45309",
        stars: 5,
        text: "Wat een geweldige investering! Dankzij de gids heb ik eindelijk geleerd hoe ik een shampoobar en solid conditioner moet maken. Mijn haar is helemaal opgeleefd, het is veel gezonder en ik bespaar elke maand een hoop geld op verzorgingsproducten. Bedankt!",
        source: "WhatsApp",
      },
    ],
  },

  autonomyIntro: {
    text1: "Met de Gids voor Natuurlijke Cosmetica leer je jouw producten helemaal vanaf nul te maken.",
    text2: "Je leert stap voor stap hoe je bewust natuurlijke ingrediënten kiest, formules aanpast voor verschillende huidtypes en haarporositeit, en producten personaliseert zodat ze perfect aansluiten bij jouw behoeften.",
    text3: "Je krijgt het vertrouwen en de volledige onafhankelijkheid om zelf formules te ontwikkelen. Je zult recepten kunnen testen en verfijnen om unieke cosmetica met een eigen karakter te creëren. Dankzij de zeer uitgebreide catalogus van natuurlijke grondstoffen leer je de beste ingrediënten kennen en ontdek je de ideale combinaties voor elk type product.",
    cta: "KOOP DE GIDS NU!",
    imageAlt: "Onafhankelijkheid in het maken van natuurlijke cosmetica",
  },

  benefitsList: {
    headline: "Onafhankelijkheid en creativiteit in de wereld van natuurlijke verzorging!",
    cta: "IK WIL NU TOEGANG!",
    items: [
      {
        bold: "Leer hoe je zelf",
        rest: " crèmes, serums, shampoos, zepen en nog veel meer verzorgingsproducten maakt.",
      },
      {
        bold: "Ontdek hoe je foutloos",
        rest: " de juiste ingrediënten kiest voor elke specifieke behoefte van huid en haar.",
      },
      {
        bold: "Bevrijd jezelf van industriële chemicaliën en",
        rest: " ontwikkel 100% gepersonaliseerde, natuurlijke formules.",
      },
      {
        bold: "Verdiep je in fytotherapie voor cosmetica,",
        rest: " en maak volop gebruik van de helende eigenschappen van kruiden en extracten.",
      },
      {
        bold: "Verlaag je uitgaven aanzienlijk",
        rest: " door je eigen cosmetica te maken, zonder ook maar iets in te leveren op kwaliteit.",
      },
      {
        bold: "Krijg toegang tot professionele recepturen",
        rest: " en leer hoe je veilig producten van de allerhoogste kwaliteit maakt.",
      },
      {
        bold: "Geef je huid de allerbeste verzorging,",
        rest: " precies wetende welke pure ingrediënten je gebruikt.",
      },
      {
        bold: "Bescherm de gezondheid van je gezin",
        rest: " met producten die vrij zijn van schadelijke conserveermiddelen en kunstmatige kleurstoffen.",
      },
    ],
  },

  economy: {
    headline: "Geld besparen en gezonde verzorging zonder een grammetje chemie!",
    text1: "Het maken van je eigen natuurlijke cosmetica is de beste manier om je huid te beschermen en tegelijkertijd enorm veel geld te besparen. Met de Gids voor Natuurlijke Cosmetica leer je hoe je producten van topkwaliteit produceert voor een fractie van de prijs van drogisterijartikelen. Zo voorkom je dat je te veel betaalt voor commerciële cosmetica vol chemicaliën, en investeer je in betaalbare, schone en zeer effectieve natuurlijke grondstoffen.",
    text2: "Dit is jouw onmisbare handboek in de overstap naar een gezondere levensstijl. Dankzij de exclusieve recepten krijg je de volledige controle terug over wat je op je lichaam smeert. Je kunt genieten van handgemaakte producten die 100% veilig, milieuvriendelijk en zacht zijn voor zowel je huid als voor de planeet.",
    cta: "IK BEGIN MET MAKEN!",
    imageAlt: "Gezonde verzorging",
  },

  finalCta: {
    urgencyLabel: "LAATSTE DAG OM TE BESTELLEN",
    urgencySub: "voor de speciale actieprijs!",
    urgencyText:
      "Dit is je absolute laatste kans om te profiteren van onze uitzonderlijke aanbieding en je aan te sluiten bij duizenden enthousiaste cursisten!",
    offerPrice: "9.90 €",
    button: "KRIJG NU TOEGANG!",
    productTitle: "Gids voor Natuurlijke Cosmetica!",
    imageAlt: "Gids voor natuurlijke cosmetica",
    bundleList: [
      "80 recepten voor natuurlijke cosmetica",
      "Uitgebreid stap-voor-stap handboek",
      "Educatief lexicon van grondstoffen",
      "Toegang tot een besloten community",
      "Ondersteuning van experts bij al je vragen",
      "Geverifieerde en betrouwbare leverancierslijst",
    ],
    timerLabels: {
      days: "Dagen",
      hours: "Uren",
      minutes: "Minuten",
      seconds: "Seconden",
    },
  },

  footer: {
    tagline: "Ontdek samen met ons hoe je de perfecte natuurlijke cosmetica maakt!",
  },
};