// lib/copy.js
export const copy = {
  checkoutUrl: "https://www.oriopay.app/p/natuurlijke-cosmetica",

  metadata: {
    title: "Gids voor Natuurlijke Cosmetica | PerfuMaria das Ervas",
    description:
      "80 recepten voor 100% natuurlijke cosmetica om thuis te maken. Geteste en bewezen formules voor eigen gebruik of om een bedrijf te starten.",
  },

  hero: {
    headlineLine1: "80 recepten voor",
    headlineHighlight: "NATUURLIJKE COSMETICA",
    subheadline:
      "Krijg toegang tot geheime recepten voor 100% natuurlijke cosmetica die je gewoon thuis kunt maken! Geteste en bewezen formules voor eigen gebruik of om je eigen bedrijf te starten.",
    cta: "IK WIL NU TOEGANG!",
    imageAlt: "Gids voor natuurlijke cosmetica",
    timerLabels: {
      days: "Dagen",
      hours: "Uren",
      minutes: "Minuten",
      seconds: "Seconden",
    },
  },

  story: {
    text: "Ik ga je nu een praktische, to-the-point en uiterst betrouwbare gids geven waarmee je thuis je eigen 100% natuurlijke cosmetica kunt maken. Zonder een fortuin uit te geven, zonder afhankelijk te zijn van duizenden ingrediënten – en met de mogelijkheid om het zelf te gebruiken, cadeau te doen aan je geliefden of zelfs te verkopen als je een nieuwe inkomstenbron wilt creëren!",
    imageAlt: "Natuurlijke cosmetica",
  },

  recipeList: {
    headline: "Maak kennis met de",
    headlineHighlight: "80 recepten",
    headlineSuffix: "waar je toegang toe krijgt in de Gids voor Natuurlijke Cosmetica:",
    cta: "IK WIL ZE HEBBEN!",
    col1: [
      "Kalmerende bodycrème",
      "Bodycrème met panthenol",
      "Verfrissende bodylotion",
      "Body soufflé",
      "Body butter met urucum",
      "Vaste body butter (Lotionbar)",
      "Bodyolie",
      "Therapeutische olie voor vlekjes en striae",
      "Tweefasen bodyolie",
      "Natuurlijke zelfbruiner",
      "Vloeibare lichaamszeep",
      "Douchegel",
      "Vaste lichaamszeep met SCI",
      "Traditionele vaste lichaamszeep",
      "Romige hydraterende zeep",
      "Exfoliërende lichaamszeep (Scrubzeep)",
      "Bodyscrub",
      "Bodyscrub met amandelmeel",
      "Natuurlijke body highlighter",
      "Bodyspray (Body Splash)",
      "Gezichtscrème met vitamine C",
      "Aftersun gezichtscrème met lavendel",
      "Gezichtscrème met klei",
      "Hydraterende gezichtslotion met jasmijn",
      "Droge gezichtsolie (Dry Oil)",
      "Vloeibare gezichtszeep",
      "Reinigend gezichtsschuim",
      "Gezichtsserum voor de droge en gevoelige huid",
      "Gezichtsserum voor de vette huid",
      "Oogserum",
      "Gezichtstoner voor de droge en gevoelige huid",
      "Verfrissende gezichtstoner voor de vette huid",
      "Reinigingsolie voor het gezicht (Cleansing Oil)",
      "Reinigingsbalsem voor het gezicht (Cleansing Balm)",
      "Zeep met rode klei – Detox en revitalisatie",
      "Milde gezichtsscrub",
      "Gezichtsgel met salicylzuur",
      "Gel-gezichtsmasker met hyaluronzuur",
      "Gezichtselixer van rozen",
      "Gezichtsspray met aloë vera",
      "Haarmasker voor krullend en golvend haar",
    ],
    col2: [
      "Haarmasker voor steil en licht golvend haar",
      "Romige conditioner",
      "Solid conditioner voor krullend en golvend haar",
      "Solid conditioner voor licht golvend en steil haar",
      "Shampoobar voor krullend en golvend haar",
      "Shampoobar voor steil en licht golvend haar",
      "Vloeibare shampoo",
      "Romige 2-in-1 shampoo",
      "Kindershampoo",
      "Leave-in conditioner",
      "Hittebeschermende haarspray",
      "Haarolie",
      "Haargel",
      "Natuurlijke haarpommade",
      "Hydraterende finish spray",
      "Hoofdhuidscrub",
      "Haargroei toner",
      "Serum voor gespleten haarpunten",
      "Haarparfum",
      "Natuurlijke intiemzeep",
      "Natuurlijke kinderzeep voor het lichaam",
      "Natuurlijk vloeibaar parfum",
      "Natuurlijk vast parfum",
      "Tandpasta in gelvorm",
      "Mondwater",
      "Deodorant spray",
      "Calendulazalf",
      "Arnicazalf",
      "Voedende lippenbalsem",
      "Natuurlijke lippenstift",
      "Natuurlijke lipscrub",
      "Make-up remover spray",
      "Scheerschuim",
      "Natuurlijke aftershave",
      "Hand- en voetcrème",
      "Wenkbrauwgel",
      "Natuurlijke massagekaars",
      "Voedend serum voor nagels en nagelriemen",
      "Natuurlijk insectenwerend middel",
      "Revitaliserend badzout",
    ],
  },

  whatYouGet: {
    headline: "WAT ONTDEK JE IN DEZE COMPLETE GIDS?",
    cta: "KOOP DE GIDS NU!",
    imageAlt: "Wat je in de gids zult ontdekken",
    items: [
      "Meer dan 80 geteste en bewezen recepten – inclusief romige scrubzeep, droge gezichtsolie, bodyspray, hittebescherming voor het haar en diverse nieuwe formules.",
      "Bases voor crèmes, gels, shampoos en zepen – leer veilige en gepersonaliseerde formules maken voor elk huid- en haartype.",
      "Een complete stap-voor-stap handleiding voor beginners en gevorderden – beheers alles, van de basisconcepten tot de meest complexe technieken.",
      "Ingrediëntencatalogus – ontdek de voordelen van verschillende natuurlijke grondstoffen om zeer effectieve cosmetica te creëren.",
      "Fytotherapie toegepast in de cosmetica – hoe je geneeskrachtige planten gebruikt om de werking van je cosmetica te versterken.",
      "De geheimen van natuurlijk formuleren – pH-waarde aanpassen, conservering, keuze van grondstoffen en effectieve combinaties.",
      "Tips voor thuis- en professionele productie – richt je eigen atelier voor natuurlijke cosmetica in en verfijn je technieken.",
      "Duurzaamheid en milieubewustzijn – leer biologisch afbreekbare en ecologische cosmetica te maken.",
    ],
  },

  testimonials: {
    headline: "BEKIJK WAT ANDEREN ZEGGEN OVER DE GIDS VOOR NATUURLIJKE COSMETICA:",
    cta: "IK WIL NU TOEGANG!",
    cards: [
      {
        name: "Sanne M.",
        initials: "SM",
        color: "#16a34a",
        stars: 5,
        text: "Ik ben helemaal weg van deze gids! Ik heb de kalmerende bodycrème en de gezichtszeep al gemaakt en ze zijn fantastisch geworden. Veel beter dan de industriële producten die ik voorheen gebruikte. Een echte aanrader!",
        source: "WhatsApp",
      },
      {
        name: "Lotte de V.",
        initials: "LV",
        color: "#0f766e",
        stars: 5,
        text: "Wauw, wat een geweldige gids! De recepten zijn super gedetailleerd en makkelijk te volgen. Ik heb zelfs al wat producten aan vriendinnen verkocht en ze zijn er dol op. Het is elke cent waard!",
        source: "WhatsApp",
      },
      {
        name: "Fleur R.",
        initials: "FR",
        color: "#7c3aed",
        stars: 5,
        text: "Ik twijfelde even om het te kopen, maar het was het absoluut waard! De grondstoffencatalogus heeft me enorm geholpen om de ingrediënten te begrijpen. Ik heb inmiddels al 6 verschillende recepten gemaakt en ze zijn allemaal perfect gelukt.",
        source: "WhatsApp",
      },
      {
        name: "Anne K.",
        initials: "AK",
        color: "#b45309",
        stars: 5,
        text: "Wat een geweldige investering! Dankzij de gids heb ik geleerd hoe ik een shampoobar en solid conditioner moet maken. Mijn haar is veel gezonder en ik bespaar elke maand een hoop geld. Bedankt!",
        source: "WhatsApp",
      },
    ],
  },

  autonomyIntro: {
    text1: "Met de Gids voor Natuurlijke Cosmetica leer je jouw cosmetica helemaal vanaf nul te maken.",
    text2: "Je leert stap voor stap hoe je natuurlijke ingrediënten kiest, formules aanpast voor verschillende huid- en haartypes, en producten personaliseert naar jouw eigen wensen.",
    text3: "Daarnaast krijg je het vertrouwen en de onafhankelijkheid om zelf formules te bedenken. Je kunt recepten testen en aanpassen om unieke producten met een eigen identiteit te creëren. Dankzij de uitgebreide catalogus van natuurlijke grondstoffen leer je de beste ingrediënten kennen en ontdek je de ideale combinaties voor elk cosmetisch product.",
    cta: "KOOP DE GIDS NU!",
    imageAlt: "Onafhankelijkheid in natuurlijke cosmetica",
  },

  benefitsList: {
    headline: "Onafhankelijkheid en creativiteit in de natuurlijke cosmetica!",
    cta: "IK WIL NU TOEGANG!",
    items: [
      {
        bold: "Leer hoe je zelf",
        rest: " crèmes, serums, shampoos, zepen en nog veel meer maakt.",
      },
      {
        bold: "Ontdek hoe je",
        rest: " de juiste ingrediënten kiest voor elke specifieke behoefte.",
      },
      {
        bold: "Word onafhankelijk van de commerciële cosmetica-industrie en",
        rest: " ontwikkel gepersonaliseerde formules.",
      },
      {
        bold: "Verdiep je in fytotherapie voor cosmetica,",
        rest: " en profiteer van de therapeutische eigenschappen van geneeskrachtige planten.",
      },
      {
        bold: "Bespaar kosten",
        rest: " door je eigen cosmetica te maken, zonder in te leveren op kwaliteit.",
      },
      {
        bold: "Krijg toegang tot professionele formules",
        rest: " en leer hoe je veilig de beste producten maakt.",
      },
      {
        bold: "Onderscheid jezelf in de markt voor natuurlijke schoonheid,",
        rest: " een sector die enorm groeit en duurzame producten waardeert.",
      },
      {
        bold: "Leer hoe je een cosmetica-atelier aan huis opzet,",
        rest: " met praktische tips voor het inrichten van je werkruimte.",
      },
    ],
  },

  economy: {
    headline: "Besparen én zakelijke kansen in de natuurlijke markt!",
    text1: "Het maken van je eigen natuurlijke cosmetica is een geweldige kans, zowel om geld te besparen als om een bedrijf te starten. Met de Gids voor Natuurlijke Cosmetica leer je hoogwaardige producten te maken tegen een lage prijs. Zo vermijd je de torenhoge kosten van conventionele producten en investeer je in betaalbare, effectieve natuurlijke ingrediënten.",
    text2: "Mocht je een eigen bedrijf willen starten, dan is dit een waardevolle gids voor het opzetten van een duurzame en winstgevende onderneming. Met exclusieve formules en praktische tips over conservering, verpakking en marketing, kun je je eigen merk voor natuurlijke cosmetica lanceren. Zo bied je handgemaakte producten aan die perfect inspelen op de trend van bewust en ecologisch consumeren.",
    cta: "KOOP DE GIDS NU!",
    imageAlt: "Ondernemen in de natuurlijke markt",
  },

  finalCta: {
    urgencyLabel: "LAATSTE DAG OM TE BESTELLEN",
    urgencySub: "voor de actieprijs!",
    urgencyText:
      "Dit is je laatste kans om te profiteren van onze speciale aanbieding en deel uit te maken van onze community met duizenden tevreden cursisten!",
    offerPrice: "9.90 €",
    button: "KRIJG NU TOEGANG!",
    productTitle: "Gids voor Natuurlijke Cosmetica!",
    imageAlt: "Gids voor natuurlijke cosmetica",
    bundleList: [
      "80 recepten voor natuurlijke cosmetica",
      "Compleet lesmateriaal",
      "Educatieve grondstoffencatalogus",
      "Community van cursisten",
      "Gespecialiseerde ondersteuning voor al je vragen",
      "Lijst met leveranciers",
    ],
    timerLabels: {
      days: "Dagen",
      hours: "Uren",
      minutes: "Minuten",
      seconds: "Seconden",
    },
  },

  footer: {
    tagline: "Ontdek hoe je de perfecte natuurlijke cosmetica maakt!",
    linkLabel: "Complete cursus natuurlijke cosmetica",
    linkHref: "https://www.perfumariadaservas.shop",
  },
};